

class Equipment:
    BLACK_JACK_HAT = "BLACK_JACK_HAT"
    HIPPO_SHOES = "HIPPO_SHOES"
    GOURMAND_HAT = "GOURMAND_HAT"
    SLOTS_VEST = "SLOTS-VEST"
    HEALTHY_GLOVES = "HEALTHY_GLOVES"
    DARLENES_CHICKEN_NUGGET_AMULET = "DARLENES_CHICKEN_NUGGET_AMULET"






# 1) BLACK JACK - BLACK HAT- IF YOU BUST GETS RID OF LAST CARD, AND YOU HAVE TO STAND -QUEST FROM ALICE
# 2) HIPPO_SHOES - HIPPO TAKES 3 SECONDS EXTRA TO APPEAR -SELL AT SHOP
# 3) gourmand hat - gain an extra food slot food cant be higher than 2 -MC NUGG REWARD LEVEL 3
# 4) SLOTS-VEST - GODO OR BAD + 10% CHANCE FOR 3RD ROLL TO MATCH FIRST ROLL -RIB DEMON SLOTS PRIZE
# 6) BODY VEST= +20 HP + 10 MP  - WE CAN BUY THIS AT THE SHOP - CHEST
# 8) darlenes nugget amulet - 1/2 stamina drain for point rolls - COMPLETE QUEST FOR DARLINE THE CHICKEN