
class Events:
    LEVEL_4_TOKEN = "LEVEL_4_TOKEN"
    LEVEL_2_TOKEN = "LEVEL_2_TOKEN"
    MISSION_A_STARTED = "MISSION_A_STARTED"
    MISSION_A_ENDED = "MISSION_A_ENDED"
    QUEST_1_BADGE = "QUEST_1_BADGE"
    QUEST_1_COIN = "QUEST_1_COIN"
    QUEST_1_COMPLETE = "QUEST_1_COMPLETE"